### ISSUE TITLE
using security.py non-interactively

### ISSUE THREAD

**Issue by svenXY** [pnasrat/yum-utils#2]
Hi,

I'm trying to use the security module non-interactively, something along the lines of

``` python
import os, sys, yum
from optparse import OptionParser

yb = yum.YumBase()

yb.preconf.disableplugin = []
yb.preconf.plugin_types = (yum.plugins.TYPE_CORE,
                                           yum.plugins.TYPE_INTERACTIVE
                                          )
opt_prsr = OptionParser()
yb.preconf.optparser = opt_prsr
yb.conf.cache = os.geteuid() != 0
opts, args = opt_prsr.parse_args([])
# The yum security plugin will crap pants if the plugin
# cmdline isn't set up:
yb.plugins.setCmdLine(opts, args)

pl = yb.doPackageLists('updates', patterns=sys.argv[1:])
```

this fails with

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/yum/__init__.py", line 911, in <lambda>
    conf = property(fget=lambda self: self._getConfig(),
  File "/usr/lib/python2.6/site-packages/yum/__init__.py", line 335, in _getConfig
    startupconf.pluginconfpath,disabled_plugins,enabled_plugins)
  File "/usr/lib/python2.6/site-packages/yum/__init__.py", line 564, in doPluginSetup
    plugin_types, confpath, disabled_plugins, enabled_plugins)
  File "/usr/lib/python2.6/site-packages/yum/plugins.py", line 167, in __init__
    self.run('config')
  File "/usr/lib/python2.6/site-packages/yum/plugins.py", line 184, in run
    func(conduitcls(self, self.base, conf, **kwargs))
  File "/usr/lib/yum-plugins/security.py", line 615, in config_hook
    conduit.registerCommand(UpdateinfoCommand())
  File "/usr/lib/python2.6/site-packages/yum/plugins.py", line 508, in registerCommand
    raise Errors.ConfigError(_('registration of commands not supported'))
yum.Errors.ConfigError: registration of commands not supported
```

I'd like to have the lists WITH the information taken from security (i.e. as if I had used --security).

Is it possible?
I know some python, but I am not overly proficient.

Thanks for any insight you might be able to provide,
Sven

**Comment by svenXY** [comment]
old and most probably no progress to be expected - closing
